streamers:
  base_url: "https://paper-api.alpaca.markets"
  #  stream_url: "wss://stream.data.alpaca.markets/v1beta1/crypto"
  stream_url: "wss://stream.data.alpaca.markets/v2/iex"

log:
  level_console: "info"
  level_file: "debug"

postgres:
  host: "localhost"
  port: 5432