alpaca:
  base_url: "https://paper-api.alpaca.markets/v2"
  api_key: "PKXBKCK7IKLM8NU23667"
  api_secret: "dtGgDo6TwcGaBhQvrcA7rTeJ3qMiieZKXhp9FaVs"

log:
  level_console: "info"
  level_file: "debug"